name = "Crows Electronic Warfare"
modname = "crowsEW"
prefix = "crowsEW"
author = "Crowdedlight"
mainprefix = "z"
sig_version = 3
reuse_private_key = false
files = [
  "mod.cpp",
  "logo_crow.paa",
  "LICENSE",
  "README.md",
]
include = ["./include"]
exclude = [
  "*.psd",
  "*.png",
  "*.tga"
]
  
key_name = "{{prefix}}_{{version}}"
authority = "{{prefix}}_{{version}}-{{git \"id 8\"}}"
  
releasebuild = [
  "@zip @crowsEW_{{version}}"
]
  
[properties]
author = "Crowdedlight"
url = "https://github.com/Crowdedlight/Crows-Electronic-Warfare"